### ISSUE TITLE
"SKNK: Glaidys Cock $v2.0-alpha.1 -" animation bug.

### ISSUE THREAD

**Issue by TinySKNK** [SL-SKNK/Glaidys#8]
Submitter: flaviagrandville resident
I've got "SKNK: Glaidys Cock $v2.0-alpha.1 -" update, put the cock on and got this: https://i.gyazo.com/1ae2dc101a571c1d527a79652ba7dd1d.png
Turned all AOs off and still have the same result. Changing position or lentgh in the HUD doesn't affect it.

**Comment by Tokeli** [comment]
W o o p s.
